### ISSUE TITLE
Portability

### ISSUE THREAD

**Issue by EtchedPixels** [ratboy666/am9511#1]
For ANSI C compilers types.h shouldn't hard coded assumptions about types in types.h as you can use

uint8_t, uint16_t etc which are ANSI stdint.h definitions - only the legacy compilers need help.

**Comment by ratboy666** [comment]
Alan

Thank you for your comment. I will adjust to the exact width types
Fixed

Fred
________________________________
From: EtchedPixels ***@***.***>
Sent: July 18, 2021 7:25 AM
To: ratboy666/am9511 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ratboy666/am9511] Portability (#1)


For ANSI C compilers types.h shouldn't hard coded assumptions about types in types.h as you can use

uint8_t, uint16_t etc which are ANSI stdint.h definitions - only the legacy compilers need help.
